[package]
name = "dh_params"
version = "0.1.0"
edition = "2024"

[dependencies]
clap ={ workspace = true, features = ["derive"] }
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"