[package]
name = "dsa_sign"
version = "0.1.0"
edition = "2024"

[dependencies]
clap ={ workspace = true, features = ["derive"] }
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2.19"
rand = "0.8"
sha2 = "0.10.9"
